### ISSUE TITLE
Question about the result

### ISSUE THREAD

**Issue by YingChen-HIT** [Freder-chen/vitp#1]
Thanks for sharing your code for us to study. However, I find out the results presented in Github are different from those in the paper. Does the Swelling-tiny indicate the ViT-P-tiny in the paper ?

I am looking forward to seeing your response.

**Comment by Freder-chen** [comment]
The preprinted paper (ViT-P) provided in readme is not the same as the method implemented in this repository (Swelling ViT), so their results are different. And we recommend using Swelling ViT for more stable results.
